### ISSUE TITLE
Backbutton redundant

### ISSUE THREAD

**Issue by Faunsce** [xornet-cloud/Xornet#203] opened 2021-07-09 17:38 UTC
The backbutton on the page performs the exact same functionality as the back button within browsers. I do remember at some point that the button functioned as a "home" button to take people back to the home page of the site. and especially since we both do not currently have a way to easily get back to the home page and a button on the dashboard that is redundant, we should just revert those changes.

**Comment by Geoxor** [comment] 2021-07-09 22:35
duplicate of #191

**Closed by Geoxor** 2021-07-09 22:35 UTC
